# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "JetBrains Mono NF Medium"
    style: Regular

  # Bold font face
  bold:
    family: "JetBrains Mono NF ExtraBold"
    style: Bold

  # Italic font face
  italic:
    family: "JetBrains Mono"
    style: Italic

  # Bold italic font face
  bold_italic:
    family: "PlemolJPConsoleNF-Italic"
    style: Bold Italic

  # Point size
  size: 15

  # Offset
  offset:
    x: 0
    y: 0

  # Glyph offset
  # glyph_offset:
  #  y: 0
  #  x: 0
